### ISSUE TITLE
Account4 cs project creates a RootNamespace and Assembly build target named Account3 in place of Account4

### ISSUE THREAD

**Issue by costarec** [pdeitel/VCSharpHTP6#1]
examples/ch04/Account4/Account4/Account4.csproj

In the csproj file there are entries on lines #10 and 11 that refers to Account3 for the RootNamespace and AssemblyName and so the build target gets written as Account3.exe when it would appear as though it should logically be named Account4.exe

I noticed this error in the source code zip examples some time back and but didn't report thinking it would be reported by others.
I should have known better. Sorry for the delay in reporting. 
Great book, been using it (and before that, the Java HTP books) for years in my classrooms with great results. --chuck

**Comment by pdeitel** [comment]
Thanks Chuck!
